/*
 * Copyright (c) 2017 iWave Systems Technologies Pvt. Ltd.
 *
 * This program is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License version 2
 * as published by the Free Software Foundation.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program; if not, write to the Free Software
 * Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA
 */

/*
 * @file mx6_iwg15m_sm.h
 *
 * @brief GPIO Defination for iMx6x SM SOMs
 *
 * @ingroup Main
 */


#include <common.h>
#include <asm/io.h>
#include <asm/arch/iomux.h>
#include <asm/arch/mx6-pins.h>
#include <asm/arch/sys_proto.h>
#include <linux/errno.h>
#include <asm/gpio.h>
#include <asm/mach-imx/iomux-v3.h>

#include <asm/arch/gpio.h>

/* Board Configutation GPIOs */
#define BRD_CFG0_GPIO  IMX_GPIO_NR(1, 5)
#define BRD_CFG1_GPIO  IMX_GPIO_NR(5, 22)
#define BRD_CFG2_GPIO  IMX_GPIO_NR(5, 23)
#define BRD_CFG3_GPIO  IMX_GPIO_NR(5, 24)
#define BRD_CFG4_GPIO  IMX_GPIO_NR(5, 25)
#define BRD_CFG5_GPIO  IMX_GPIO_NR(7, 0)
#define BRD_CFG6_GPIO  IMX_GPIO_NR(7, 1)

/*  Unused GPIO pins */

#define MX6_PAD_GPIO_2__GPIO1_IO02		IMX_GPIO_NR(1, 2)
#define MX6_PAD_SD2_CLK__GPIO1_IO10		IMX_GPIO_NR(1, 10)
#define MX6_PAD_SD2_CMD__GPIO1_IO11		IMX_GPIO_NR(1, 11)
#define MX6_PAD_SD1_DAT0__GPIO1_IO16		IMX_GPIO_NR(1, 16)
#define MX6_PAD_SD1_CLK__GPIO1_IO20		IMX_GPIO_NR(1, 20)
#define MX6_PAD_SD1_DAT3__GPIO1_IO21		IMX_GPIO_NR(1, 21)
#define MX6_PAD_ENET_RX_ER__GPIO1_IO24		IMX_GPIO_NR(1, 24)
#define MX6_PAD_ENET_CRS_DV__GPIO1_IO25		IMX_GPIO_NR(1, 25)

#define MX6_PAD_NANDF_D0__GPIO2_IO00		IMX_GPIO_NR(2, 0)
#define MX6_PAD_NANDF_D1__GPIO2_IO01		IMX_GPIO_NR(2, 1)
#define MX6_PAD_NANDF_D2__GPIO2_IO03		IMX_GPIO_NR(2, 2)
#define MX6_PAD_NANDF_D3__GPIO2_IO03		IMX_GPIO_NR(2, 3)
#define MX6_PAD_NANDF_D4__GPIO2_IO04		IMX_GPIO_NR(2, 4)
#define MX6_PAD_NANDF_D5__GPIO2_IO05		IMX_GPIO_NR(2, 5)
#define MX6_PAD_NANDF_D6__GPIO2_IO06		IMX_GPIO_NR(2, 6)
#define MX6_PAD_NANDF_D7__GPIO2_IO07		IMX_GPIO_NR(2, 7)

#define  MX6_PAD_KEY_COL2__GPIO4_IO10		IMX_GPIO_NR(4, 10)
#define  MX6_PAD_KEY_ROW2__GPIO4_IO11		IMX_GPIO_NR(4, 11)
#define  MX6_PAD_KEY_COL3__GPIO4_IO12		IMX_GPIO_NR(4, 12)
#define  MX6_PAD_KEY_ROW3__GPIO4_IO13		IMX_GPIO_NR(4, 13)
#define  MX6_PAD_DI0_PIN4__GPIO4_IO20		IMX_GPIO_NR(4, 20)

#define  MX6_PAD_MX6_PAD_EIM_A25__GPIO5_IO02	IMX_GPIO_NR(5, 2)
#define  MX6_PAD_CSI0_PIXCLK__GPIO5_IO18	IMX_GPIO_NR(5, 18)
#define  MX6_PAD_CSI0_MCLK__GPIO5_IO19		IMX_GPIO_NR(5, 19)
#define  MX6_PAD_CSI0_DATA_EN__GPIO5_IO20	IMX_GPIO_NR(5, 20)
#define  MX6_PAD_CSI0_VSYNC__GPIO5_IO21		IMX_GPIO_NR(5, 21)
#define  MX6_PAD_CSI0_DAT12__GPIO5_IO30		IMX_GPIO_NR(5, 30)
#define  MX6_PAD_CSI0_DAT13__GPIO5_IO31		IMX_GPIO_NR(5, 31)

#define  MX6_PAD_CSI0_DAT14__GPIO6_IO00		IMX_GPIO_NR(6, 0)
#define  MX6_PAD_CSI0_DAT15__GPIO6_IO01		IMX_GPIO_NR(6, 1)
#define  MX6_PAD_NANDF_CLE__GPIO6_IO07		IMX_GPIO_NR(6, 7)
#define  MX6_PAD_NANDF_ALE__GPIO6_IO08		IMX_GPIO_NR(6, 8)
#define  MX6_PAD_NANDF_WP_B__GPIO6_IO09		IMX_GPIO_NR(6, 9)
#define  MX6_PAD_NANDF_RB0__GPIO6_IO10		IMX_GPIO_NR(6, 10)
#define  MX6_PAD_NANDF_CS0__GPIO6_IO11		IMX_GPIO_NR(6, 11)
#define  MX6_PAD_NANDF_CS1__GPIO6_IO14		IMX_GPIO_NR(6, 14)
#define  MX6_PAD_NANDF_CS2__GPIO6_IO15		IMX_GPIO_NR(6, 15)
#define  MX6_PAD_NANDF_CS3__GPIO6_IO16		IMX_GPIO_NR(6, 16)
#define  MX6_PAD_EIM_BCLK__GPIO6_IO31		IMX_GPIO_NR(6, 31)

#define  MX6_PAD_GPIO_16__GPIO7_IO11		IMX_GPIO_NR(7, 11)
#define  MX6_PAD_GPIO_17__GPIO7_IO12		IMX_GPIO_NR(7, 12)
#define  MX6_PAD_GPIO_18__GPIO7_IO13		IMX_GPIO_NR(7, 13)



iomux_v3_cfg_t unused_gpio_pads_pmic[] = {
	IOMUX_PADS(PAD_GPIO_2__GPIO1_IO02	| MUX_PAD_CTRL(NO_PAD_CTRL)),
	IOMUX_PADS(PAD_SD2_CLK__GPIO1_IO10	| MUX_PAD_CTRL(NO_PAD_CTRL)),
	IOMUX_PADS(PAD_SD2_CMD__GPIO1_IO11	| MUX_PAD_CTRL(NO_PAD_CTRL)),
	IOMUX_PADS(PAD_SD1_DAT0__GPIO1_IO16	| MUX_PAD_CTRL(NO_PAD_CTRL)),
	IOMUX_PADS(PAD_SD1_CLK__GPIO1_IO20	| MUX_PAD_CTRL(NO_PAD_CTRL)),
	IOMUX_PADS(PAD_SD1_DAT3__GPIO1_IO21	| MUX_PAD_CTRL(NO_PAD_CTRL)),
	IOMUX_PADS(PAD_ENET_RX_ER__GPIO1_IO24	| MUX_PAD_CTRL(NO_PAD_CTRL)),
	IOMUX_PADS(PAD_ENET_CRS_DV__GPIO1_IO25	| MUX_PAD_CTRL(NO_PAD_CTRL)),

	IOMUX_PADS(PAD_NANDF_D0__GPIO2_IO00	| MUX_PAD_CTRL(NO_PAD_CTRL)),
	IOMUX_PADS(PAD_NANDF_D1__GPIO2_IO01	| MUX_PAD_CTRL(NO_PAD_CTRL)),
	IOMUX_PADS(PAD_NANDF_D2__GPIO2_IO02	| MUX_PAD_CTRL(NO_PAD_CTRL)),
	IOMUX_PADS(PAD_NANDF_D3__GPIO2_IO03	| MUX_PAD_CTRL(NO_PAD_CTRL)),
	IOMUX_PADS(PAD_NANDF_D4__GPIO2_IO04	| MUX_PAD_CTRL(NO_PAD_CTRL)),
	IOMUX_PADS(PAD_NANDF_D5__GPIO2_IO05	| MUX_PAD_CTRL(NO_PAD_CTRL)),
	IOMUX_PADS(PAD_NANDF_D6__GPIO2_IO06	| MUX_PAD_CTRL(NO_PAD_CTRL)),
	IOMUX_PADS(PAD_NANDF_D7__GPIO2_IO07	| MUX_PAD_CTRL(NO_PAD_CTRL)),

	IOMUX_PADS(PAD_KEY_COL2__GPIO4_IO10	| MUX_PAD_CTRL(NO_PAD_CTRL)),
	IOMUX_PADS(PAD_KEY_ROW2__GPIO4_IO11	| MUX_PAD_CTRL(NO_PAD_CTRL)),
	IOMUX_PADS(PAD_KEY_COL3__GPIO4_IO12	| MUX_PAD_CTRL(NO_PAD_CTRL)),
	IOMUX_PADS(PAD_KEY_ROW3__GPIO4_IO13	| MUX_PAD_CTRL(NO_PAD_CTRL)),
	IOMUX_PADS(PAD_DI0_PIN4__GPIO4_IO20	| MUX_PAD_CTRL(NO_PAD_CTRL)),

	IOMUX_PADS(PAD_EIM_A25__GPIO5_IO02	| MUX_PAD_CTRL(NO_PAD_CTRL)),
	IOMUX_PADS(PAD_CSI0_PIXCLK__GPIO5_IO18	| MUX_PAD_CTRL(NO_PAD_CTRL)),
	IOMUX_PADS(PAD_CSI0_MCLK__GPIO5_IO19	| MUX_PAD_CTRL(NO_PAD_CTRL)),
	IOMUX_PADS(PAD_CSI0_DATA_EN__GPIO5_IO20	| MUX_PAD_CTRL(NO_PAD_CTRL)),
	IOMUX_PADS(PAD_CSI0_VSYNC__GPIO5_IO21	| MUX_PAD_CTRL(NO_PAD_CTRL)),
	IOMUX_PADS(PAD_CSI0_DAT12__GPIO5_IO30	| MUX_PAD_CTRL(NO_PAD_CTRL)),
	IOMUX_PADS(PAD_CSI0_DAT13__GPIO5_IO31	| MUX_PAD_CTRL(NO_PAD_CTRL)),

	IOMUX_PADS(PAD_CSI0_DAT14__GPIO6_IO00	| MUX_PAD_CTRL(NO_PAD_CTRL)),
	IOMUX_PADS(PAD_CSI0_DAT15__GPIO6_IO01	| MUX_PAD_CTRL(NO_PAD_CTRL)),
	IOMUX_PADS(PAD_NANDF_CLE__GPIO6_IO07	| MUX_PAD_CTRL(NO_PAD_CTRL)),
	IOMUX_PADS(PAD_NANDF_ALE__GPIO6_IO08	| MUX_PAD_CTRL(NO_PAD_CTRL)),
	IOMUX_PADS(PAD_NANDF_WP_B__GPIO6_IO09	| MUX_PAD_CTRL(NO_PAD_CTRL)),
	IOMUX_PADS(PAD_NANDF_RB0__GPIO6_IO10	| MUX_PAD_CTRL(NO_PAD_CTRL)),
	IOMUX_PADS(PAD_NANDF_CS0__GPIO6_IO11	| MUX_PAD_CTRL(NO_PAD_CTRL)),
	IOMUX_PADS(PAD_NANDF_CS1__GPIO6_IO14	| MUX_PAD_CTRL(NO_PAD_CTRL)),
	IOMUX_PADS(PAD_NANDF_CS2__GPIO6_IO15	| MUX_PAD_CTRL(NO_PAD_CTRL)),
	IOMUX_PADS(PAD_NANDF_CS3__GPIO6_IO16	| MUX_PAD_CTRL(NO_PAD_CTRL)),
	IOMUX_PADS(PAD_EIM_BCLK__GPIO6_IO31	| MUX_PAD_CTRL(NO_PAD_CTRL)),

	IOMUX_PADS(PAD_GPIO_16__GPIO7_IO11	| MUX_PAD_CTRL(NO_PAD_CTRL)),
	IOMUX_PADS(PAD_GPIO_17__GPIO7_IO12	| MUX_PAD_CTRL(NO_PAD_CTRL)),
	IOMUX_PADS(PAD_GPIO_18__GPIO7_IO13	| MUX_PAD_CTRL(NO_PAD_CTRL)),
};

int unused_gpio_pmic[] = {
	MX6_PAD_GPIO_2__GPIO1_IO02,
	MX6_PAD_SD2_CLK__GPIO1_IO10,
	MX6_PAD_SD2_CMD__GPIO1_IO11,
	MX6_PAD_SD1_DAT0__GPIO1_IO16,
	MX6_PAD_SD1_CLK__GPIO1_IO20,
	MX6_PAD_SD1_DAT3__GPIO1_IO21,
	MX6_PAD_ENET_RX_ER__GPIO1_IO24,
	MX6_PAD_ENET_CRS_DV__GPIO1_IO25,

	MX6_PAD_NANDF_D0__GPIO2_IO00,
	MX6_PAD_NANDF_D1__GPIO2_IO01,
	MX6_PAD_NANDF_D2__GPIO2_IO03,
	MX6_PAD_NANDF_D3__GPIO2_IO03,
	MX6_PAD_NANDF_D4__GPIO2_IO04,
	MX6_PAD_NANDF_D5__GPIO2_IO05,
	MX6_PAD_NANDF_D6__GPIO2_IO06,
	MX6_PAD_NANDF_D7__GPIO2_IO07,

	MX6_PAD_KEY_COL2__GPIO4_IO10,
	MX6_PAD_KEY_ROW2__GPIO4_IO11,
	MX6_PAD_KEY_COL3__GPIO4_IO12,
	MX6_PAD_KEY_ROW3__GPIO4_IO13,
	MX6_PAD_DI0_PIN4__GPIO4_IO20,

	MX6_PAD_MX6_PAD_EIM_A25__GPIO5_IO02,
	MX6_PAD_CSI0_PIXCLK__GPIO5_IO18,
	MX6_PAD_CSI0_MCLK__GPIO5_IO19,
	MX6_PAD_CSI0_DATA_EN__GPIO5_IO20,
	MX6_PAD_CSI0_VSYNC__GPIO5_IO21,
	MX6_PAD_CSI0_DAT12__GPIO5_IO30,
	MX6_PAD_CSI0_DAT13__GPIO5_IO31,

	MX6_PAD_CSI0_DAT14__GPIO6_IO00,
	MX6_PAD_CSI0_DAT15__GPIO6_IO01,
	MX6_PAD_NANDF_CLE__GPIO6_IO07,
	MX6_PAD_NANDF_ALE__GPIO6_IO08,
	MX6_PAD_NANDF_WP_B__GPIO6_IO09,
	MX6_PAD_NANDF_RB0__GPIO6_IO10,
	MX6_PAD_NANDF_CS0__GPIO6_IO11,
	MX6_PAD_NANDF_CS1__GPIO6_IO14,
	MX6_PAD_NANDF_CS2__GPIO6_IO15,
	MX6_PAD_NANDF_CS3__GPIO6_IO16,
	MX6_PAD_EIM_BCLK__GPIO6_IO31,

	MX6_PAD_GPIO_16__GPIO7_IO11,
	MX6_PAD_GPIO_17__GPIO7_IO12,
	MX6_PAD_GPIO_18__GPIO7_IO13,
};

iomux_v3_cfg_t board_config_pads_bom[] = {
	IOMUX_PADS(PAD_GPIO_5__GPIO1_IO05	| MUX_PAD_CTRL(NO_PAD_CTRL)),
	IOMUX_PADS(PAD_CSI0_DAT4__GPIO5_IO22	| MUX_PAD_CTRL(NO_PAD_CTRL)),
	IOMUX_PADS(PAD_CSI0_DAT5__GPIO5_IO23	| MUX_PAD_CTRL(NO_PAD_CTRL)),
	IOMUX_PADS(PAD_CSI0_DAT6__GPIO5_IO24	| MUX_PAD_CTRL(NO_PAD_CTRL)),
	IOMUX_PADS(PAD_CSI0_DAT7__GPIO5_IO25	| MUX_PAD_CTRL(NO_PAD_CTRL)),
};

int board_config_gpio_bom[] = {
	BRD_CFG0_GPIO,
	BRD_CFG1_GPIO,
	BRD_CFG2_GPIO,
	BRD_CFG3_GPIO,
	BRD_CFG4_GPIO,
};

iomux_v3_cfg_t board_config_pads_som[] = {
	IOMUX_PADS(PAD_SD3_DAT5__GPIO7_IO00	| MUX_PAD_CTRL(NO_PAD_CTRL)),
	IOMUX_PADS(PAD_SD3_DAT4__GPIO7_IO01	| MUX_PAD_CTRL(NO_PAD_CTRL)),
	IOMUX_PADS(PAD_GPIO_4__GPIO1_IO04	| MUX_PAD_CTRL(NO_PAD_CTRL)),
};

int board_config_gpio_som[] = {
	BRD_CFG5_GPIO,
	BRD_CFG6_GPIO,
};

